<?php

$works = [
  [
    'title' => 'Pointer',
    'status' => 'In Development',
    'rubro' => 'rubro_real_estate',
    'cat' => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link' => 'https://prueba.pointer.uy/',
    'desk' => 'pointer.uy.webp',
    'private' => false,
  ],
  [
    'title' => 'Silent Room',
    'status' => 'Completed',
    'rubro' => 'rubro_communication_agencies',
    'cat' => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link' => 'https://silentroomstudio.com/',
    'desk' => 'silentroomstudio.com.webp',
    'private' => false,
  ],
  [
    'title' => 'Alohaus',
    'status' => 'Completed',
    'rubro' => 'rubro_communication_agencies',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://alohaus.uy',
    'desk'  => 'www.alohaus.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Agencia Inbloom',
    'status' => 'Completed',
    'rubro' => 'rubro_communication_agencies',
    'cat' => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link' => 'https://agenciainbloom.com.br',
    'desk' => 'agenciainbloom.com.br_.webp',
    'private' => false,
  ],
  [
    'title' => 'Buenaventura Films',
    'status' => 'Completed',
    'rubro' => 'rubro_communication_agencies',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://buenaventurafilms.com',
    'desk'  => 'buenaventurafilms.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Moviruta',
    'status' => 'In Development',
    'rubro' => 'rubro_automotive',
    'cat' => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link' => 'https://moviruta.nicolasgonzalez.dev/',
    'desk' => 'moviruta.uy.webp',
    'private' => false,
  ],
  [
    'title' => 'Pet Cremation',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://pet-cremation.org/',
    'desk'  => 'pet-cremation.org.webp',
    'private' => false,
  ],
  [
    'title' => 'Jeydi',
    'status' => 'Completed',
    'rubro' => 'rubro_freelancers',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://jeydi.com.uy/',
    'desk'  => 'jeydi.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Bercetche',
    'status' => 'Completed',
    'rubro' => 'rubro_architects',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://bercetche.com/',
    'desk'  => 'bercetche.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Jorge Barrera & Asociados',
    'status' => 'Completed',
    'rubro' => 'rubro_law_firms',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://estudiobarrera.com.uy/',
    'desk'  => 'estudiobarrera.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Bull Advisor',
    'status' => 'Completed',
    'rubro' => 'rubro_accounting_firms',
    'cat'   => 'one-page',
    'category' => 'One Page',
    'link'  => 'https://bulladvisors.com.uy/',
    'desk'  => 'bulladvisors.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Vetcross',
    'status' => 'Completed',
    'rubro' => 'rubro_laboratories',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://vetcross.com',
    'desk'  => 'www.vetcross.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Estética Los Angeles',
    'status' => 'Completed',
    'rubro' => 'rubro_aesthetic_clinics',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://esteticalosangeles.com.br/',
    'desk'  => 'esteticalosangeles.com.br_.webp',
    'private' => false,
  ],
  [
    'title' => 'Nomia',
    'status' => 'Completed',
    'rubro' => 'rubro_software_companies',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://www.nomia.com.uy',
    'desk'  => 'www.nomia.com.uy_sitio_.webp',
    'private' => false,
  ],
  [
    'title' => 'LSI',
    'status' => 'Completed',
    'rubro' => 'rubro_laboratories',
    'cat'   => 'one-page',
    'category' => 'One Page',
    'link'  => 'https://lsi.com.uy',
    'desk'  => 'lsi.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'E2B',
    'status' => 'Completed',
    'rubro' => 'rubro_educational_institutions',
    'cat'   => 'one-page',
    'category' => 'One Page',
    'link'  => 'https://e2b.com.uy',
    'desk'  => 'e2b.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Pulso',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://pulso.com.uy',
    'desk'  => 'www.pulso.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Dellavale & Balbi Abogados',
    'status' => 'Completed',
    'rubro' => 'rubro_law_firms',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://dellavallebalbi.com.uy/',
    'desk'  => 'dellavallebalbi.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Green Ray LED',
    'status' => 'Completed',
    'rubro' => 'rubro_lighting_companies',
    'cat'   => 'ecommerce',
    'category' => 'Ecommerce',
    'link'  => 'https://greenrayled.com',
    'desk'  => 'greenrayled.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Habit',
    'status' => 'Completed',
    'rubro' => 'rubro_accommodation_companies',
    'cat'   => 'one-page',
    'category' => 'One Page',
    'link'  => 'https://www.habit.com.uy',
    'desk'  => 'www.habit.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Agroenfoque',
    'status' => 'Completed',
    'rubro' => 'rubro_laboratories',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://agroenfoque.com.uy',
    'desk'  => 'www.agroenfoque.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'I3',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'one-page',
    'category' => 'One Page',
    'link'  => 'https://i3.com.uy',
    'desk'  => 'i3.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'AVP Farma',
    'status' => 'Completed',
    'rubro' => 'rubro_laboratories',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://avpfarma.com.uy',
    'desk'  => 'avpfarma.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Navegante',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'ecommerce',
    'category' => 'Ecommerce',
    'link'  => 'https://navegante.com.uy',
    'desk'  => 'navegante.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'STTAFF',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://sttaff.com.uy',
    'desk'  => 'sttaff.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'ADUR Ciencias',
    'status' => 'Completed',
    'rubro' => 'rubro_universities',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://adurciencias.fcien.edu.uy',
    'desk'  => 'adurciencias.fcien.edu.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Cursos y Viajes',
    'status' => 'Completed',
    'rubro' => 'rubro_educational_institutions',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://cursosyviajes.com',
    'desk'  => 'cursosyviajes.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Mitra',
    'status' => 'Completed',
    'rubro' => 'rubro_communication_agencies',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://mitra.com.uy',
    'desk'  => 'mitra.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Juventud',
    'status' => 'Completed',
    'rubro' => 'rubro_sports_clubs',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://juventud.uy',
    'desk'  => 'juventud.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Pro Work Gestion',
    'status' => 'Completed',
    'rubro' => 'rubro_freelancers',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://proworkgestion.com',
    'desk'  => 'proworkgestion.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Felipe',
    'status' => 'Completed',
    'rubro' => 'rubro_freelancers',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://www.felipedg.com',
    'desk'  => 'www.felipedg.com_.webp',
    'private' => false,
  ],
  [
    'title' => 'Zander',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://zander.uy',
    'desk'  => 'zander.uy_.webp',
    'private' => false,
  ],

  // PRIVATE

  [
    'title' => 'iHouse',
    'status' => 'Completed',
    'rubro' => 'rubro_architects',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://ihouse.com.uy',
    'desk'  => 'ihouse.com.uy_.webp',
    'private' => true,
  ],

  [
    'title' => 'FDG',
    'status' => 'Completed',
    'rubro' => 'rubro_architects',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://fdg.com.uy',
    'desk'  => 'fdg.com.uy_.webp',
    'private' => true,
  ],

  [
    'title' => 'DDC',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://ddc.com.uy/',
    'desk'  => 'ddc.com.uy.webp',
    'private' => true,
  ],

  [
    'title' => 'Moaa',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://moaa.com.uy',
    'desk'  => 'moaa.com.uy_.webp',
    'private' => true,
  ],

  [
    'title' => 'Reducto',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://reducto.uy',
    'desk'  => 'reducto.uy_.webp',
    'private' => true,
  ],

  [
    'title' => 'Roberto Canessa',
    'status' => 'Completed',
    'rubro' => 'rubro_freelancers',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://robertocanessa.com',
    'desk'  => 'robertocanessa.com_.webp',
    'private' => true,
  ],

  [
    'title' => 'Acorner',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://acorner.es',
    'desk'  => 'acorner.es_.webp',
    'private' => true,
  ],
  [
    'title' => 'Onalake',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://onalake.com.uy',
    'desk'  => 'onalake.com.uy_.webp',
    'private' => true,
  ],

    [
    'title' => 'REM',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://rem.com.uy',
    'desk'  => 'rem.com.uy_.webp',
    'private' => true,
  ],
  
  [
    'title' => 'Angra',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://angra.com.uy',
    'desk'  => 'angra.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Angus Las Morochas',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://anguslasmorochas.com.uy',
    'desk'  => 'anguslasmorochas.com.uy.webp',
    'private' => true,
  ],
  [
    'title' => 'Apiter',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://apiter.com',
    'desk'  => 'apiter.com_en_.webp',
    'private' => true,
  ],
  [
    'title' => 'Born',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://born.com.uy',
    'desk'  => 'born.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Estudio Bornia',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://estudiobornia.com',
    'desk'  => 'estudiobornia.com_.webp',
    'private' => true,
  ],
  [
    'title' => 'Everdem',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://everdem.com',
    'desk'  => 'everdem.com.webp',
    'private' => true,
  ],
  [
    'title' => 'Greenmed',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://greenmed.uy',
    'desk'  => 'greenmed.uy_en_.webp',
    'private' => true,
  ],
  [
    'title' => 'HMA',
    'status' => 'Completed',
    'rubro' => 'rubro_law_firms',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://hma.uy',
    'desk'  => 'hma.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'La Rábida',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://larabida.com.uy',
    'desk'  => 'larabida.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'La Reserva Lagos',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://lareservalagos.com.uy',
    'desk'  => 'lareservalagos.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Los Cardinales',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://loscardinales.com.uy',
    'desk'  => 'loscardinales.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Mane',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://mane.com.uy',
    'desk'  => 'mane.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Mind Latam',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://mindlatam.com',
    'desk'  => 'mindlatam.com_.webp',
    'private' => true,
  ],

  [
    'title' => 'Ojos Ignacio',
    'status' => 'Completed',
    'rubro' => 'rubro_industrial',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://ojoseignacio.com',
    'desk'  => 'ojoseignacio.com_.webp',
    'private' => true,
  ],

  [
    'title' => 'Southeast',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://southeast.com.uy',
    'desk'  => 'southeast.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Studio 4D Urban Real Estate',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'static-site',
    'category' => 'Static Site',
    'link'  => 'https://studio4d.com',
    'desk'  => 'studio4d.com_urban-real-estate-development.webp',
    'private' => true,
  ],
  [
    'title' => 'Terramar Farmlands',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://terramarfarmlands.com',
    'desk'  => 'terramarfarmlands.com_.webp',
    'private' => true,
  ],
  [
    'title' => 'Cambio Suizo',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://www.cambiosuizo.com.uy',
    'desk'  => 'www.cambiosuizo.com.uy_.webp',
    'private' => false,
  ],
  [
    'title' => 'Plaza Correo',
    'status' => 'Completed',
    'rubro' => 'rubro_services',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://www.plazacorreo.com.uy',
    'desk'  => 'www.plazacorreo.com.uy_.webp',
    'private' => true,
  ],
  [
    'title' => 'Xigna',
    'status' => 'Completed',
    'rubro' => 'rubro_real_estate',
    'cat'   => 'dynamic-site',
    'category' => 'Dynamic Site',
    'link'  => 'https://xigna.com.uy',
    'desk'  => 'xigna.com.uy_.webp',
    'private' => true,
  ],

];
